# {{ProjectName}} API Documentation

## {{PluralEntityName}}

Base route:

```text
/api/v{{ApiVersion}}/{{Route}}
```

## Endpoints

| Method | Route | Description |
| --- | --- | --- |
| GET | `/api/v{{ApiVersion}}/{{Route}}` | Gets all {{PluralEntityName}}. |
| GET | `/api/v{{ApiVersion}}/{{Route}}/{id}` | Gets a {{EntityName}} by primary key. |
| POST | `/api/v{{ApiVersion}}/{{Route}}` | Creates a new {{EntityName}}. |
| PUT | `/api/v{{ApiVersion}}/{{Route}}/{id}` | Updates an existing {{EntityName}}. |
| DELETE | `/api/v{{ApiVersion}}/{{Route}}/{id}` | Deletes a {{EntityName}}. |

## Entity

| Field | Value |
| --- | --- |
| Entity | `{{EntityName}}` |
| Table | `{{TableName}}` |
| Primary Key | `{{PrimaryKey}}` |
| Primary Key Type | `{{PrimaryKeyType}}` |

Generated by {{Author}} on {{Date}}.
