# {{ProjectName}} Architecture

## Overview

{{ProjectName}} uses Clean Architecture to keep domain logic independent from infrastructure, API, and client concerns.

## Layers

| Layer | Responsibility |
| --- | --- |
| Domain | Entities, repository contracts, domain events, and domain rules. |
| Application | DTOs, requests, responses, services, managers, validation, and mapping. |
| Infrastructure | Dapper repositories, SQL Server connection management, and persistence concerns. |
| API | ASP.NET Core controllers, middleware, Swagger configuration, and HTTP contracts. |
| Client | Angular, React, or Blazor UI components and API clients. |

## Generated Entity

`{{EntityName}}` maps to the `{{TableName}}` SQL Server table.

## Database

The application uses SQL Server stored procedures for data access.

## Version

API Version: `{{ApiVersion}}`

Generated by {{Author}} on {{Date}}.
