# {{ProjectName}}

{{ProjectName}} is an enterprise application generated from MCPTools templates.

## Overview

This solution follows Clean Architecture and separates domain, application, infrastructure, API, and client concerns.

## Technology

- .NET 10
- C# 14
- ASP.NET Core
- Dapper
- SQL Server
- Stored Procedures
- Nullable Reference Types

## Solution

```text
{{SolutionName}}
```

## Entity

Primary generated entity: `{{EntityName}}`

## Author

Generated by {{Author}} on {{Date}}.
