<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Abstractions\" />
    <Folder Include="Configuration\" />
    <Folder Include="Constants\" />
    <Folder Include="Exceptions\" />
    <Folder Include="Extensions\" />
    <Folder Include="Tools\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Models\" />
    <Folder Include="Versioning\" />
    <Folder Include="Utilities\" />
    <Folder Include="Templates\" />
    <Folder Include="TemplateEngine\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
  </ItemGroup>

</Project>
